### ISSUE TITLE
DBT 0.21.0 requires new configuration to override global DBT macros

### ISSUE THREAD

**Issue by mroy-seedbox** [marco-roy/DDO#1]
See https://docs.getdbt.com/reference/dbt-jinja-functions/dispatch#overriding-global-macros

```
dispatch:
  - macro_namespace: dbt
    search_order: ['my_project/my_package', 'dbt']
```

**Comment by AdrianCio** [comment]
@mroy-seedbox did you get this to work? I'm struggling with this

**Comment by mroy-seedbox** [comment]
Yup, all you need is something like this in your `dbt_project.yml`:

```yml
name: my_project

# Allow my macros to override global DBT macros
dispatch:
  - macro_namespace: dbt
    search_order: ['my_project', 'dbt']
```

**Comment by AdrianCio** [comment]
This is strange, I did this but it gives me `No materialization 'plain' was found for adapter postgres! (searched types 'default' and 'postgres')`

**Comment by mroy-seedbox** [comment]
That is weird indeed! But I've never tested it with Postgres (only with Snowflake)... maybe there's something missing to make it work? 🤔

**Comment by mroy-seedbox** [comment]
Try with something like this:

```yml
# Allow my macros & DDO macros to override global DBT macros
dispatch:
  - macro_namespace: dbt
    search_order: ['my_project', 'dbt_packages/DDO/macros', 'dbt']
```

**Comment by AdrianCio** [comment]
Same issue :( 

```
macro-paths: 
  - "macros"
  - dbt_modules/DDO/macros/materializations

# Allow my macros & DDO macros to override global DBT macros
dispatch:
  - macro_namespace: dbt
    search_order: ['my_project', 'dbt_modules/DDO/macros', 'dbt']
```

**Comment by mroy-seedbox** [comment]
Try with `dbt_packages/` instead of `dbt_modules/`.

`dbt_modules/` was for older versions of DBT.

**Comment by AdrianCio** [comment]
Same result with this config. It is a good point that I was using the old name, but unfortunately it didn't change the output.
I also ran a quick test where I removed `dbt_packages` from `clean-targets` but again, same result as in my previous post.
```
macro-paths: 
  - "macros"
  - dbt_packages/DDO/macros/materializations

# Allow my macros & DDO macros to override global DBT macros
dispatch:
  - macro_namespace: dbt
    search_order: ['my_project', 'dbt_packages/DDO/macros', 'dbt']

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  ```
